version: '3'
services:
  appeal-app:
    build: .
    container_name: mps_client
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      API_URL: ${API_URL}
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"